### ISSUE TITLE
Thanks for great app. Could you add support for DirectML/ONNX/OpenVino acceleration and LCM/SD-Turbo/SDXS/Hyper SD/SDXL-Lightning models, please?

### ISSUE THREAD

**Issue by JohnClaw** [aagdev/mlimgsynth#1]
...

**Comment by aagdev** [comment]
I have no plan to support others backends besides GGML (at least in the short term). GGML has support for GPU acceleration and in the latest version the Vulkan performance has improved.

Regarding distilled models (LCM/Lightining/Turbo/Hyper) it should  be possible to run them, but the quality may not be the best due to missing sampling methods. I do plan to add more methods when I have the time.

**Comment by JohnClaw** [comment]
Thanks for answer. Good luck in developing of this nice project.
